/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author acerpc
 */
public class Panel_Usuario extends javax.swing.JPanel {

    /**
     * Creates new form Panel_Usuario
     */
    public Panel_Usuario() {
        initComponents();
    }
    
    public String devolverContraseña()
    {
        return this.jpf_Contraseña.getText();
    }
    
    public String devolverContraseñaRepetidad()
    {
        return this.jpf_ConttraseñaRepetida.getText();
    }
    
    public String[] devolverInformacion()
    {
        String []arreglo= new String[4];
        arreglo[0]=this.jt_Cedula.getText();
        arreglo[1]=this.jt_NombreCompleto.getText();
        arreglo[2]=this.jt_NombreUsuario.getText();
        arreglo[3]=this.jpf_Contraseña.getText();
        
        return arreglo;
    }
    
    public void resetearGUI()
    {
        this.jt_Cedula.setText("");
        this.jt_NombreCompleto.setText("");
        this.jt_NombreUsuario.setText("");
        this.jpf_Contraseña.setText("");
        this.jpf_ConttraseñaRepetida.setText("");
    }
    
    public void resetearContraseñas()
    {
        this.jpf_Contraseña.setText("");
        this.jpf_ConttraseñaRepetida.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jl_Cedula = new javax.swing.JLabel();
        jl_RepetirContraseña = new javax.swing.JLabel();
        jl_NombreCompleto = new javax.swing.JLabel();
        jl_NombreUsuario = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jt_Cedula = new javax.swing.JTextField();
        jt_NombreCompleto = new javax.swing.JTextField();
        jt_NombreUsuario = new javax.swing.JTextField();
        jl_Contraseña = new javax.swing.JLabel();
        jpf_Contraseña = new javax.swing.JPasswordField();
        jpf_ConttraseñaRepetida = new javax.swing.JPasswordField();

        jLabel3.setText("jLabel3");

        jl_Cedula.setText("Cedula");

        jl_RepetirContraseña.setText("Repetir Contraseña");

        jl_NombreCompleto.setText("Nombre Completo");

        jl_NombreUsuario.setText("Nombre Usuario");

        jl_Contraseña.setText("Contraseña");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jl_RepetirContraseña)
                    .addComponent(jl_NombreUsuario)
                    .addComponent(jl_NombreCompleto)
                    .addComponent(jl_Cedula)
                    .addComponent(jLabel6)
                    .addComponent(jl_Contraseña))
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jt_NombreUsuario)
                    .addComponent(jt_NombreCompleto)
                    .addComponent(jt_Cedula)
                    .addComponent(jpf_Contraseña)
                    .addComponent(jpf_ConttraseñaRepetida, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_Cedula)
                    .addComponent(jt_Cedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_NombreCompleto)
                    .addComponent(jt_NombreCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_NombreUsuario)
                    .addComponent(jt_NombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jl_Contraseña)
                    .addComponent(jpf_Contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_RepetirContraseña)
                    .addComponent(jpf_ConttraseñaRepetida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jl_Cedula;
    private javax.swing.JLabel jl_Contraseña;
    private javax.swing.JLabel jl_NombreCompleto;
    private javax.swing.JLabel jl_NombreUsuario;
    private javax.swing.JLabel jl_RepetirContraseña;
    private javax.swing.JPasswordField jpf_Contraseña;
    private javax.swing.JPasswordField jpf_ConttraseñaRepetida;
    private javax.swing.JTextField jt_Cedula;
    private javax.swing.JTextField jt_NombreCompleto;
    private javax.swing.JTextField jt_NombreUsuario;
    // End of variables declaration//GEN-END:variables
}
